name: e
favicon: null
layout_spectrum: 0.5142250973731279
typography_spectrum: 0.4878044275101274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5842961552552879
  lightness: 0.8589743934571743
  saturation: 0.9940423334483057
  rhythmicContrast: 0.21936968294903636
purpose: []
